import class16
book1 = class16.Book('tytuł','ja',100)
book1.open()
book1.book_status()
book1.next_page()
book1.read()
book1.next_page()
book1.read()
book1.next_page()
book1.read()
book1.next_page()
book1.read()
book1.previous_page()
book1.read()
book1.book_status()
book1.close()
book1.read()